{{- if .Values.configOverride }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: {{ .Release.Namespace | quote }}
data:
  config: |
{{ .Values.configOverride | nindent 4 }}
{{- end }}
